<?php

namespace DebatBundle\Repository;

use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\EntityRepository;

/**
 * DebatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DebatRepository extends EntityRepository
{
    protected $objectManager;
    protected $class;
    protected $repository;

    //$repository=$this->getDoctrine()->getManager()->getRepository('DebatBundle::Debat');

/*    public function __construct(ObjectManager $om, $class)
    {

        $em = $this->getDoctrine()->getEntityManager();

        $this->objectManager = $om;
        $this->repository = $om->getRepository($class);

        $metadata = $om->getClassMetadata($class);
        $this->class = $metadata->getName();
    }*/

    public function myFindAll()
    {
        return $this->createQueryBuilder('a')->getQuery()->getResult();
    }


}
